FROM pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime

WORKDIR /ChildrenBookServer

RUN pip install Flask
RUN pip install sentencepiece
RUN pip install -U "huggingface_hub[cli]"
RUN pip install flask-cors
RUN pip install python-dotenv
RUN pip install requests
RUN pip install -U google-generativeai
RUN pip install hf_xet
RUN pip install diffusers transformers accelerate
RUN pip install -q -U "google-genai>=1.0.0"
# Copy application files into the container
COPY . .

EXPOSE 5000

CMD ["python", "./app.py"]
